### ISSUE TITLE
Missing Device Option

### ISSUE THREAD

**Issue by Cinux90** [donvipre/ansible-role-docker_handbrake#1]
As already implemented in the [docker_makemkv role](https://github.com/donvipre/ansible-role-docker_makemkv/blob/master/tasks/install.yml#L22).
A Variable to set a Device is very helpful :)

I tested it already some weeks ago without any issues.

**Comment by donvipre** [comment]
Done with: e2c2340f18a847f6e4ec5eb56952ecdc35c3a003
